### ISSUE TITLE
Testing: Unit test does not complete without failure

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2023sp-420-MediaTek#176]
```
    Traceback (most recent call last):
      File "/Users/wkillian/Desktop/MediaTek/test/unittests.py", line 118, in <module>
        ut.testInvalidPangram()
      File "/Users/wkillian/Desktop/MediaTek/test/unittests.py", line 39, in testInvalidPangram
        assert self.userReq == "empty"
               ^^^^^^^^^^^^^^^^^^^^^^^
    AssertionError
```

**Comment by SteamsDev** [comment]
Assertion errors addressed during testing (also reformatted testing module to address other issues)
